/** Language versions this toolchain understands (see docs/SPEC.md §4). */
export const SUPPORTED_DSL_VERSIONS = ["1.0"] as const;
export type DslVersion = (typeof SUPPORTED_DSL_VERSIONS)[number];

/** The JSON Schema of the AST (generated by `scripts/gen-ast-schema.mjs`); structured-output engines can use it directly. */
export { default as AST_SCHEMA } from "../schema/ast.schema.json";
